config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about',  as: 'about'  #url => controller#action
  #resource: maps HTTP verbs to controller after: (rake routes)
  #resources :posts 
  resources :posts do 
    resources :comments # nested in the post route
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many  :comments
    validates :title, presence: true,
                      length: {minimum:5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    http_basic_authenticate_with name: "Marco", password: "1234", except: [:index, :show]

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def show 
        @comment = Comment.find(params[:id])
    end
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end 
    def destroy
        @post = Post.find(params[:post_id])
        #@comment = @post.comments.find(params[:id])
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
    private def comment_params
        params.require(:comment).permit(:username, :body)
    end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About us'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end 

    def show 
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end
    def create
        #render plain: params[:post].inspect
        @post = Post.new(post_params)
        #actually save in the db
        
        if(@post.save)
            redirect_to @post
        else 
            render 'new'
        end
    end
    def edit
        @post = Post.find(params[:id])

    end
    def update 
        @post = Post.find(params[:id])
        #actually update in the db        
        if(@post.update(post_params))
            redirect_to @post
        else 
            render 'edit'
        end
    end

    def destroy 
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private def post_params 
        params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<hr>
<h3>Comments</h3>
<% @post.comments.each do |c| %>
    <h4> <%= c.username %> </h4>
    <p> <%= c.body %> </p>

     <%= link_to "Delete Comment", [c.post,c], method:  :delete, data: {confirm: 'Are you sure?'} , :class => "red" %>

<% end %>

app/views/comments/_form.html.erb
<hr>
<h3>Add Comment</h3>
<%= form_for([@post,@post.comments.build])  do |f| %>    
    <p>
        <%= f.label :username %><br>
        <%= f.text_field(:username, {:class => 'red'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area  :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/comments/show.html.erb
<h2><%= @comment.username %></h2>
<p><%= @comment.body %></p>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFeatures</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li> <%= link_to "Home", home_path %></li>
      <li> <%= link_to "About", about_path %></li>
      <li> <%= link_to "Create Post", new_post_path %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about</h1>
<p><%= @title %></p>

app/views/posts/edit.html.erb
<h1> Edit Post</h1>
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |m| %>
        <p style="color: red"><%= m %></p>
    <%end%>    
<%end%>
<%= form_for :post, url: post_path(@post), method: :patch  do |f| %>    
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'red'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area  :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Posts List</h1>

<% @posts.each do |p| %>
    <h2> <%= p.title %> </h1>
    <p> <%= p.body %> </p>
    <%= link_to "Read More", post_path(p) %>
<% end %>

app/views/posts/new.html.erb
<h1> Add Post</h1>
<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |m| %>
        <p style="color: red"><%= m %></p>
    <%end%>    
<%end%>
<%= form_for :post, url: posts_path do |f| %>    
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'red'}) %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area  :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete,  data: {confirm: "Are you sure??"}, :class => "red" %>


<%= render 'comments/comments' %>
<%= render 'comments/form' %>